version: "3.5"
services:

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    volumes:
      - ../database/neo4j:/data
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    networks:
      - net
  
  jupyter:
    image: neo4j_ia_jupyter
    ports:
      - 8888:8888
    networks:
      - net
    volumes:
      - ../notebooks:/project/notebooks
    env_file:
      - ../.env

volumes:
  index_data:
    driver: local

networks:
  net:
    driver: bridge